### ISSUE TITLE
Encryption and decryption do not work in edit mode

### ISSUE THREAD

**Issue by kuzmandi** [cosmocode/dokuwiki-plugin-encryptedpasswords#12]
**Since upgrading to *Igor* and a recent version of the *Encrypted Passwords Plugin*, I have the following behavior:**

I can decrypt passwords saved in previous versions with no problem. If I click on the field with the dots and enter the passphrase it is copied to the clipboard, if I click on the lock and enter the passphrase it is displayed. When I edit the wiki page I see what I saw earlier also, the encrypted text inside <decrypt></decrypt> tags. This is also how the file is stored on disk.

**I only noticed that something was wrong when I wanted to change/add a password. In the edit mode of the wiki page nothing works:**

When I click on the key icon ("Add password") <encrypt></encrypt> tags are inserted or the selected text is enclosed with these tags. When saving the wiki page it will ask for a passphrase, the text will be saved unchanged (and readable) with the <encrypt></encrypt> tags on disk. So in my case like this:

```
====== New test page ======
<encrypt>strictly_secret_text</encrypt>
```

But the wiki pages saved from earlier look like this:

```
====== Existing page ======
<decrypt>XD5PGTU [...] </decrypt>
```

When I click on the decrypt icon ("Decrypt all entries") nothing happens, no matter if I selected text or not.

Please support me in this matter, I am grateful for any help.

- *DokuWiki Release 2022-07-31a "Igor"*
- *encryptedpasswords 2022-08-06*

**Comment by DeanCording** [comment]
I've looked into this a little bit and it appears that the encryption handler isn't being connected to the Save button onClick event. Not sure why, but this plugin is the only one I could find that works this way, so it's not surprising it broke.

**Comment by smarteyesi** [comment]
the same happens with subsection edits (made possible by either FastWiki or WiderEdit plugin). 

There are 2 scenario's which sometimes happens:
1) the passwords are not encrypted even though the password popup field has been shown
2) you cannot click on the lock (to indicate you want to encrypt the passwords)

**Comment by splitbrain** [comment]
Are you guys all using the fastwiki plugin?

**Comment by DeanCording** [comment]
> Are you guys all using the fastwiki plugin?

Yes, and I can confirm that issue disappears if I disable the fastwiki plugin

**Comment by smarteyesi** [comment]
@DeanCording we have sponsored the fix for this plugin to work with the fastwiki plugin. It should be published soon

**Comment by DeanCording** [comment]
Can confirm that the update fixes this problem with fastwiki.  Thanks
