### ISSUE TITLE
Decrypt of legacy passwords fails

### ISSUE THREAD

**Issue by DeanCording** [cosmocode/dokuwiki-plugin-encryptedpasswords#4]
Recently upgraded to version 2022-03-16 and now it will not decrypt my existing passwords.

Have confirmed that the encryption is valid using the command:

  echo 'U2FsdGVkX19mBmpZ2Jq67aUTk7Qo1PgMqveRhAK90MI=' | openssl base64 -d |openssl aes-256-cbc -d -md md5

**Comment by DeanCording** [comment]
Looking into this some more.  It is the _copy to clipboard_ function that fails - displaying them in the clear  works ok.

In PageHandling.js the `showClear` function calls `this.aes.autodecrypt(cipher, passphrase)` whereas `copyHandler` calls `this.aes.decrypt(cipher, passphrase)`.  `copyHandler` should call `autodcrypt`

**Comment by tiltX** [comment]
Hi,
could you please make this fix available to the dokuwiki update mechanism? I've noticed that you have upgraded the version in commit 377e2ad3879fedb8493a6c76f65077fcf892415e but the extension manager still shows 2022-03-16 as the latest version available.

Thank you.
