### ISSUE TITLE
How to decrypt old passwords?

### ISSUE THREAD

**Issue by Harliff** [cosmocode/dokuwiki-plugin-encryptedpasswords#5]
I have passwords begining with U1FsdGVkX1
Which command could be used to decrypt them?

**Comment by DeanCording** [comment]
$> echo 'U2FsdGVkX1/oynrOig+RoUwMNCHvJH2bcmQeAq2xaLI=' | openssl base64 -d |openssl aes-256-cbc -d -md md5
