### ISSUE TITLE
[DE] Schlüsselicon wird nicht angezeigt

### ISSUE THREAD

**Issue by TheFrodo** [cosmocode/dokuwiki-plugin-encryptedpasswords#6]
Hallo zusammen,

Ich schreib das hier mal auf Deutsch. :) 

Ich hab das Plugin gerade installiert, und wollte es im playground ausprobieren. Leider erscheint bei mir das Schlüsselicon nicht. (siehe screenshot).

Das DokuWiki ist komplett neu, da wurden noch keine Einstellungen getätigt.

![DokuWiki](https://user-images.githubusercontent.com/28831127/182781378-c05b9834-539c-414b-bcc0-94df9f769c01.png)

**Comment by splitbrain** [comment]
Either plugin wasn't correctly installed, the cache hasn't been updated or some JavaScript error occurred. This report does not contain enough info for any further debugging.
